### ISSUE TITLE
Docker開発時等ホットリロードを対応する

### ISSUE THREAD

**Issue by niwaniwa** [niwaniwa/Sakura-API#13]
# とは
- dockerフォルダに分かれてるけどなぜ？
    - postgresqlしか書いてないけどrust部分はdockerに書かないんだっけ？

**Comment by niwaniwa** [comment]
@suba327777 何も分かってない

**Comment by suba327777** [comment]
@niwaniwa 
それに関しては書いてもいいし、書かなくてもいいって感じかな
でも、開発する中で恩恵を得られるケースもあるから書くか
