### ISSUE TITLE
config/環境変数について

### ISSUE THREAD

**Issue by niwaniwa** [niwaniwa/Sakura-API#15]
# 概要
接続するためのURLや鍵情報などをハードコーディングではなくconfigなどから取得したい

# 解決策
このあたり良さそう
- [confy](https://github.com/rust-cli/confy)

意見求む @suba327777

**Comment by suba327777** [comment]
@niwaniwa 
confy 初見だなあ
今まではdotenvとか使ってたけど、使いやすいと思ったのでいいと思う！
